# Generated by Django 5.2.7 on 2025-10-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo_primario', models.CharField(choices=[('aire', 'Aire'), ('agua', 'Agua'), ('tierra', 'Tierra'), ('fuego', 'Fuego'), ('luz', 'Luz'), ('oscuridad', 'Oscuridad'), ('plasma', 'Plasma')], max_length=20)),
                ('tipo_secundario', models.CharField(blank=True, choices=[('aire', 'Aire'), ('agua', 'Agua'), ('tierra', 'Tierra'), ('fuego', 'Fuego'), ('luz', 'Luz'), ('oscuridad', 'Oscuridad'), ('plasma', 'Plasma')], max_length=20, null=True)),
                ('descripcion', models.TextField()),
                ('ataque', models.IntegerField()),
                ('defensa', models.IntegerField()),
                ('velocidad', models.IntegerField()),
                ('salud', models.IntegerField()),
            ],
        ),
    ]
