# Generated by Django 5.2.7 on 2025-12-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criaturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criatura',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='criaturas/'),
        ),
    ]
